In [1]:
import numpy as np

# Create the 2D array
arr = np.array([[6, -8, 73, -110],
                [np.nan, -8, 0, 94]])

# Replace NaN with 0
arr = np.nan_to_num(arr, nan=0)

print("Array after replacing NaN with 0:")
print(arr)

# Interchange 3 rows and 3 columns (transpose)
arr_transposed = arr.T

print("\nArray after interchanging rows and columns:")
print(arr_transposed)

Array after replacing NaN with 0:
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]

Array after interchanging rows and columns:
[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [2]:
import numpy as np

# Create a 3D array of shape (2, 3, 4)
arr = np.arange(24).reshape(2, 3, 4)

print("Original Array:")
print(arr)
print("Original Shape:", arr.shape)

# Move axis 0 to position 2
new_arr = np.moveaxis(arr, 0, 2)

print("\nArray after moving axis 0 to position 2:")
print(new_arr)
print("New Shape:", new_arr.shape)

Original Array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Original Shape: (2, 3, 4)

Array after moving axis 0 to position 2:
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]
New Shape: (3, 4, 2)


In [6]:
import numpy as np

# Create array with NaN values
arr = np.array([[10, 20, np.nan],
                [40, np.nan, 60],
                [70, 80, 90]])

print("Original Array:")
print(arr)

# Calculate column-wise mean ignoring NaN values
col_mean = np.nanmean(arr, axis=0)

# Replace NaN values with corresponding column means
inds = np.where(np.isnan(arr))
arr[inds] = np.take(col_mean, inds[1])

print("\nArray after replacing NaN with column averages:")
print(arr)

Original Array:
[[10. 20. nan]
 [40. nan 60.]
 [70. 80. 90.]]

Array after replacing NaN with column averages:
[[10. 20. 75.]
 [40. 50. 60.]
 [70. 80. 90.]]


In [7]:
import numpy as np

# Create NumPy array
arr = np.array([10, -5, 20, -8, 15, -3])

print("Original Array:")
print(arr)

# Replace negative values with 0
arr[arr < 0] = 0

print("\nArray after replacing negative values with 0:")
print(arr)

Original Array:
[10 -5 20 -8 15 -3]

Array after replacing negative values with 0:
[10  0 20  0 15  0]
