In [13]:
# Combining a one and a two-dimensional NumPy Array
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([[4,5,6],[7,8,9]])
newarr1 = np.concatenate((arr1, arr2.flatten())) # this is used to combine the one and two-dimensional array into a single one-dimensional array
print(newarr1)
newarr2 = np.vstack((arr1, arr2)) # this is used to combine the one and two-dimensional array into a single two-dimensional array
print(newarr2)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
# Flatten a 2d numpy array into 1d array 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
newarr = arr.flatten() # this is used to flatten a 2d array into a 1d array
print(newarr)

[1 2 3 4 5 6 7 8 9]


In [15]:
# Reverse a numpy array
arr = np.array([1,2,3,4,5])
newarr = arr[::-1] # this is used to reverse a numpy array
print(newarr)

[5 4 3 2 1]


In [21]:
# Practice operations like Get the maximum value from given array. Get the minimum value from given array. Find the number of rows and columns of a given array using NumPy. Select the elements from a given array (each element and specific element). Find the sum of values in a 2D array using for loop. Adding, Subtracting, multiplying, dividing arrays in Numpy.
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Maximum value in the array:", np.max(arr))
print("Minimum value in the array:", np.min(arr))
print("Number of rows and columns in the array:", arr.shape)
# selecting each element from the array
for i in arr:
    for j in i:
        print(j)
# selecting specific element from the array
print("Specific element from the array:", arr[1][2]) # this will select the element at index 1 and 2 which is 6
print("Sum of values in the 2D array:", np.sum(arr))
# sum of values in the 2D array using for loop
sum = 0
for i in arr:
    for j in i:
        sum += j
print("Sum of values in the 2D array using for loop:", sum)


Maximum value in the array: 9
Minimum value in the array: 1
Number of rows and columns in the array: (3, 3)
1
2
3
4
5
6
7
8
9
Specific element from the array: 6
Sum of values in the 2D array: 45
Sum of values in the 2D array using for loop: 45


In [19]:
# Adding, Subtracting, multiplying, dividing arrays in Numpy
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[9,8,7],[6,5,4],[3,2,1]])
print("Addition of two arrays:\n", np.add(arr1, arr2))
print("Subtraction of two arrays:\n", np.subtract(arr1, arr2))
print("Multiplication of two arrays:\n", np.multiply(arr1, arr2))
print("Division of two arrays:\n", np.divide(arr1, arr2))

Addition of two arrays:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction of two arrays:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Multiplication of two arrays:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Division of two arrays:
 [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [ ]:
# Iterate 3D array using for loop and nditer
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("Iterating 3D array using for loop:") 
for i in arr:
    for j in i:
        for k in j:
            print(k)
print("Iterating 3D array using nditer:")
for i in np.nditer(arr):
    print(i)


Iterating 3D array using for loop:
1
2
3
4
5
6
7
8
9
10
11
12
Iterating 3D array using nditer:
1
2
3
4
5
6
7
8
9
10
11
12


In [23]:
# Study the following program import numpy as np # create a numpy 1d-arrays arr1 = np.array([3, 4]) arr2 = np.array([1, 0]) # find average of NumPy arrays avg = (arr1 + arr2) / 2 print("Average of NumPy arrays:\n", avg)
import numpy as np
arr1 = np.array([3, 4])
arr2 = np.array([1, 0])
avg = (arr1 + arr2) / 2
print("Average of NumPy arrays:\n", avg)
# Calculate average mean median mode values of two NumPy 2d-arrays.
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[9,8,7],[6,5,4],[3,2,1]])
print("Average of two arrays:\n", (arr1 + arr2) / 2)

Average of NumPy arrays:
 [2. 2.]
Average of two arrays:
 [[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
