In [1]:
#  Create numpy array and perform following operations:
import numpy as np
# Convert 1D array to 2D
arr_1d = np.array([1, 2, 3, 4, 5, 6])
arr_2d = arr_1d.reshape(2, 3)
print("Original 1D array:\n", arr_1d)
print("Converted 2D array:\n", arr_2d)
# same could be done by using np.newaxis
arr_2d_newaxis = arr_1d[np.newaxis, :].reshape(2, 3)
print("Converted 2D array using np.newaxis:\n", arr_2d_newaxis)
# also same could be done by using np.expand_dims
arr_2d_expand_dims = np.expand_dims(arr_1d, axis=0).reshape(2, 3)
print("Converted 2D array using np.expand_dims:\n", arr_2d_expand_dims)
# same could be done by using np.atleast_2d
arr_2d_atleast_2d = np.atleast_2d(arr_1d).reshape(2, 3)
print("Converted 2D array using np.atleast_2d:\n", arr_2d_atleast_2d)
# same could be done by using np.array with ndmin parameter
arr_2d_ndmin = np.array(arr_1d, ndmin=2).reshape(2, 3)
print("Converted 2D array using np.array with ndmin parameter:\n", arr_2d_ndmin)
# same using vstack
arr_2d_vstack = np.vstack((arr_1d[:3], arr_1d[3:]))
print("Converted 2D array using np.vstack:\n", arr_2d_vstack)

Original 1D array:
 [1 2 3 4 5 6]
Converted 2D array:
 [[1 2 3]
 [4 5 6]]
Converted 2D array using np.newaxis:
 [[1 2 3]
 [4 5 6]]
Converted 2D array using np.expand_dims:
 [[1 2 3]
 [4 5 6]]
Converted 2D array using np.atleast_2d:
 [[1 2 3]
 [4 5 6]]
Converted 2D array using np.array with ndmin parameter:
 [[1 2 3]
 [4 5 6]]
Converted 2D array using np.vstack:
 [[1 2 3]
 [4 5 6]]


In [2]:
# Print Array Attributes(Like shape, dimenssion, data type, itemsize) 
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)
print("Shape of the array:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Data type of the array:", arr.dtype)
print("Size of each element in bytes:", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape of the array: (2, 3)
Number of dimensions: 2
Data type of the array: int64
Size of each element in bytes: 8


In [3]:
#  Create a 3×3 NumPy array of all 9 
arr = np.full((3, 3), 9)
print(arr)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [4]:
# Create a 1D array of 10 evenly spaced 
# values between 25 and 125
arr = np.linspace(25, 125, 10)
print(arr)

[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]


In [5]:
# Convert a Python list into a NumPy array
python_list = [1, 2, 3, 4, 5]
numpy_array = np.array(python_list)
print("Python list:", python_list)
print("Converted NumPy array:", numpy_array)

Python list: [1, 2, 3, 4, 5]
Converted NumPy array: [1 2 3 4 5]


In [6]:
# Reverse a 1D NumPy array
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print("Original array:", arr)
print("Reversed array:", reversed_arr)

Original array: [1 2 3 4 5]
Reversed array: [5 4 3 2 1]


In [7]:
# Create a 4×4×3 array and extract value at its second set, first row and last column
arr_3d = np.random.rand(4, 4, 3)
print("3D Array:\n", arr_3d)
extracted_value = arr_3d[1, 0, -1]
print("Extracted value at secon" \
"d set, first row and last column:", extracted_value)

3D Array:
 [[[9.80939788e-01 1.85896969e-01 3.94796327e-01]
  [2.06109957e-01 7.67319570e-01 2.45553852e-01]
  [7.29232687e-01 8.46473848e-02 8.72368692e-01]
  [1.82766137e-01 3.22909843e-01 3.30255204e-01]]

 [[6.19036016e-01 7.42750792e-01 2.80234915e-01]
  [1.09239259e-01 6.62289682e-01 3.48678437e-01]
  [6.90972391e-01 2.93023580e-01 3.12854072e-01]
  [2.99807226e-01 8.71384317e-01 2.03934400e-01]]

 [[6.54365613e-01 4.14967434e-01 5.06515329e-01]
  [7.63107391e-01 5.30809448e-01 6.60257543e-01]
  [1.56494064e-01 4.04305530e-01 6.72924759e-01]
  [3.10455452e-01 7.96806148e-01 9.11892570e-01]]

 [[2.62790247e-01 3.46029563e-01 9.02099123e-02]
  [1.56653873e-01 2.39450417e-04 4.03858637e-01]
  [7.92600021e-01 6.14664156e-01 5.31029108e-01]
  [2.57169402e-01 6.09907275e-01 7.45930910e-01]]]
Extracted value at second set, first row and last column: 0.2802349152019298


In [8]:
# Create a 4×4 and Extract Odd Rows and Even Columns 
arr_4x4 = np.random.rand(4, 4)
print("Original 4x4 Array:\n", arr_4x4)
odd_rows_even_cols = arr_4x4[1::2, ::2]
print("Extracted Odd Rows and Even Columns:\n", odd_rows_even_cols)

Original 4x4 Array:
 [[0.52881736 0.10012922 0.33574909 0.21747569]
 [0.3962702  0.72904618 0.03617661 0.29938014]
 [0.42141172 0.72630805 0.0458693  0.6433011 ]
 [0.73888233 0.15870625 0.07259402 0.22616572]]
Extracted Odd Rows and Even Columns:
 [[0.3962702  0.03617661]
 [0.73888233 0.07259402]]


In [9]:
# Slice the first two rows and first two columns of econd set from a 4×4×3 array
arr_3d = np.random.rand(4, 4, 3)
print("3D Array:\n", arr_3d)
sliced_arr = arr_3d[1, :2, :2]
print("Sliced array (first two rows and first two columns of second set):\n", sliced_arr)

3D Array:
 [[[0.09260107 0.69442518 0.74588315]
  [0.63842041 0.40780311 0.14585486]
  [0.27634464 0.95843179 0.57753943]
  [0.72347447 0.68420627 0.24729382]]

 [[0.05898094 0.83469998 0.98398033]
  [0.0913176  0.68464941 0.35060639]
  [0.95401319 0.24156535 0.3230186 ]
  [0.09577786 0.47667742 0.47663858]]

 [[0.84878077 0.57461688 0.6922174 ]
  [0.54147008 0.80177384 0.35206157]
  [0.25604331 0.16960814 0.1806723 ]
  [0.42247358 0.62709156 0.35242352]]

 [[0.18410195 0.26575825 0.8646862 ]
  [0.11703143 0.12814637 0.48818736]
  [0.95506061 0.38635611 0.19890736]
  [0.13079247 0.73504135 0.42518942]]]
Sliced array (first two rows and first two columns of second set):
 [[0.05898094 0.83469998]
 [0.0913176  0.68464941]]


In [10]:
#  Replace all odd numbers in a NumPy array with -1 by itterating using for loop [[23, 56, 78, 93], [71, 82,13, 24]]
arr = np.array([[23, 56, 78, 93], [71, 82, 13, 24]])
print("Original array:\n", arr)
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if arr[i, j] % 2 != 0:
            arr[i, j] = -1
print("Array after replacing odd numbers with -1:\n", arr)

Original array:
 [[23 56 78 93]
 [71 82 13 24]]
Array after replacing odd numbers with -1:
 [[-1 56 78 -1]
 [-1 82 -1 24]]


In [11]:
# Get the indices of non-zero elements in an array [1, 0, 2, 0, 3, 0, 4]
arr = np.array([1, 0, 2, 0, 3, 0, 4])
non_zero_indices = np.nonzero(arr)
print("Indices of non-zero elements:", non_zero_indices)

Indices of non-zero elements: (array([0, 2, 4, 6]),)


In [12]:
# Perform arithmetic operations on two NumPy arrays element-wise. Add two NumPy arrays element by element. Multiply two NumPy arrays element by element.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
sum_arr = arr1 + arr2
diff_arr = arr1 - arr2
prod_arr = arr1 * arr2
quot_arr = arr1 / arr2
print("Element-wise sum:", sum_arr)
print("Element-wise difference:", diff_arr)
print("Element-wise product:", prod_arr)
print("Element-wise quotient:", quot_arr)

Element-wise sum: [5 7 9]
Element-wise difference: [-3 -3 -3]
Element-wise product: [ 4 10 18]
Element-wise quotient: [0.25 0.4  0.5 ]


In [13]:
# Write a code to compute the dot product of two NumPy arrays arr1 = [15, 20, 25] arr2 = [10,40,37]
arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])
dot_product = np.dot(arr1, arr2)
print("Dot product of arr1 and arr2:", dot_product)

Dot product of arr1 and arr2: 1875
